"""SlideDesignProposal — per-slide design brief for the hybrid slide mode (SLIDE-04).

Written to workdir/design_proposal/slide_XX.json after the LLM generates a brief
for each storyboard slide. The user can read these briefs to understand what each
slide should visually contain before dropping their own slides into slides_user/.
"""
from __future__ import annotations

from pydantic import BaseModel, Field


class SlideDesignProposal(BaseModel):
    """Per-slide design brief written to workdir/design_proposal/slide_XX.json (SLIDE-04).

    Generated by SlidesHybridStage via forced tool-use (emit_design_proposal) from
    the storyboard spec. Provides a human-readable brief for the user to reference
    when creating or selecting their own slides.

    Attributes:
        slide_index: Zero-based index of the storyboard slide this brief covers.
        title: Slide title (mirrors storyboard SlideSpec.title).
        bullets: Key bullet points the slide should communicate.
        visual_type: Recommended VisualType enum value as a plain string
            (e.g. "bullets", "chart", "diagram").
        layout_notes: Free-text design guidance (composition, emphasis, typography).
        suggested_colors: Optional list of hex color codes suggested for this slide.
    """

    slide_index: int
    title: str
    bullets: list[str]
    visual_type: str  # VisualType enum value as plain string
    layout_notes: str  # free-text design guidance for the user
    suggested_colors: list[str] = Field(default_factory=list)
